name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 02 * * *'
    - cron: '30 13 * * *'

jobs:
  run-postman-tests:
    runs-on: ec2 github runner2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.3.0
        with:
          node-version: '20'

      - name: Install Newman and Html-extra globally
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the postman collection with newman
        run: |
          newman run "Inwarranty flow CLI.postman_collection.json" \
          -e "QA.postman_environment.json" \
          -r cli,htmlextra \
          --reporter-htmlextra-export ./newman/index.html

      - name: Newman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Newman Report
          path: newman/*.html

      - name: creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v16
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{secrets.EMAIL_PASSWORD }}
          subject: Pheonix Inwarranty flow Execution Notification
          to: roshan.shresthama@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
              Hi,
              Phoenix Inwarranty flows has been excuted and report has been publish and the url is 
              https://roshankrishnadas.github.io/Pheonix-Inwarranty/
          
          
          
          
          
          
        
        
          
